### ISSUE TITLE
plase up to img format new

### ISSUE THREAD

**Issue by SEPTIA21** [adnanzainal21/ESPENERO-WEBSITE#1]
img new format gooooo
![logo_smp-removebg-preview](https://user-images.githubusercontent.com/127393910/235166758-e4347e81-9347-473f-9819-5280a7346ea2.png)

**Comment by adnanzainal21** [comment]
ok septia done

**Comment by adnanzainal21** [comment]
[LICENSE.txt](https://github.com/adnanzainal21/ESPENERO-WEBSITE/files/11354165/LICENSE.txt)

done gooo

**Comment by adnanzainal21** [comment]
wesssssssssss
